spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl
    username: root
    password: 7639867

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql